// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control_weights.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_control_5fweights_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_control_5fweights_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_control_5fweights_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_control_5fweights_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_control_5fweights_2eproto;
class SchedulingWeights;
struct SchedulingWeightsDefaultTypeInternal;
extern SchedulingWeightsDefaultTypeInternal _SchedulingWeights_default_instance_;
class UeWeight;
struct UeWeightDefaultTypeInternal;
extern UeWeightDefaultTypeInternal _UeWeight_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::SchedulingWeights* Arena::CreateMaybeMessage<::SchedulingWeights>(Arena*);
template<> ::UeWeight* Arena::CreateMaybeMessage<::UeWeight>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class SchedulingWeights final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SchedulingWeights) */ {
 public:
  inline SchedulingWeights() : SchedulingWeights(nullptr) {}
  ~SchedulingWeights() override;
  explicit PROTOBUF_CONSTEXPR SchedulingWeights(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SchedulingWeights(const SchedulingWeights& from);
  SchedulingWeights(SchedulingWeights&& from) noexcept
    : SchedulingWeights() {
    *this = ::std::move(from);
  }

  inline SchedulingWeights& operator=(const SchedulingWeights& from) {
    CopyFrom(from);
    return *this;
  }
  inline SchedulingWeights& operator=(SchedulingWeights&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SchedulingWeights& default_instance() {
    return *internal_default_instance();
  }
  static inline const SchedulingWeights* internal_default_instance() {
    return reinterpret_cast<const SchedulingWeights*>(
               &_SchedulingWeights_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SchedulingWeights& a, SchedulingWeights& b) {
    a.Swap(&b);
  }
  inline void Swap(SchedulingWeights* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SchedulingWeights* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SchedulingWeights* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SchedulingWeights>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SchedulingWeights& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SchedulingWeights& from) {
    SchedulingWeights::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SchedulingWeights* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SchedulingWeights";
  }
  protected:
  explicit SchedulingWeights(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUeWeightsFieldNumber = 3,
    kRanIndexFieldNumber = 1,
    kTtiIndexFieldNumber = 2,
  };
  // repeated .UeWeight ue_weights = 3;
  int ue_weights_size() const;
  private:
  int _internal_ue_weights_size() const;
  public:
  void clear_ue_weights();
  ::UeWeight* mutable_ue_weights(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UeWeight >*
      mutable_ue_weights();
  private:
  const ::UeWeight& _internal_ue_weights(int index) const;
  ::UeWeight* _internal_add_ue_weights();
  public:
  const ::UeWeight& ue_weights(int index) const;
  ::UeWeight* add_ue_weights();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UeWeight >&
      ue_weights() const;

  // uint32 ran_index = 1;
  void clear_ran_index();
  uint32_t ran_index() const;
  void set_ran_index(uint32_t value);
  private:
  uint32_t _internal_ran_index() const;
  void _internal_set_ran_index(uint32_t value);
  public:

  // uint32 tti_index = 2;
  void clear_tti_index();
  uint32_t tti_index() const;
  void set_tti_index(uint32_t value);
  private:
  uint32_t _internal_tti_index() const;
  void _internal_set_tti_index(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SchedulingWeights)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UeWeight > ue_weights_;
    uint32_t ran_index_;
    uint32_t tti_index_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_control_5fweights_2eproto;
};
// -------------------------------------------------------------------

class UeWeight final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:UeWeight) */ {
 public:
  inline UeWeight() : UeWeight(nullptr) {}
  ~UeWeight() override;
  explicit PROTOBUF_CONSTEXPR UeWeight(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UeWeight(const UeWeight& from);
  UeWeight(UeWeight&& from) noexcept
    : UeWeight() {
    *this = ::std::move(from);
  }

  inline UeWeight& operator=(const UeWeight& from) {
    CopyFrom(from);
    return *this;
  }
  inline UeWeight& operator=(UeWeight&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UeWeight& default_instance() {
    return *internal_default_instance();
  }
  static inline const UeWeight* internal_default_instance() {
    return reinterpret_cast<const UeWeight*>(
               &_UeWeight_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(UeWeight& a, UeWeight& b) {
    a.Swap(&b);
  }
  inline void Swap(UeWeight* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UeWeight* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UeWeight* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UeWeight>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UeWeight& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UeWeight& from) {
    UeWeight::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UeWeight* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "UeWeight";
  }
  protected:
  explicit UeWeight(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRntiFieldNumber = 1,
    kWeightFieldNumber = 2,
  };
  // uint32 rnti = 1;
  void clear_rnti();
  uint32_t rnti() const;
  void set_rnti(uint32_t value);
  private:
  uint32_t _internal_rnti() const;
  void _internal_set_rnti(uint32_t value);
  public:

  // float weight = 2;
  void clear_weight();
  float weight() const;
  void set_weight(float value);
  private:
  float _internal_weight() const;
  void _internal_set_weight(float value);
  public:

  // @@protoc_insertion_point(class_scope:UeWeight)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t rnti_;
    float weight_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_control_5fweights_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SchedulingWeights

// uint32 ran_index = 1;
inline void SchedulingWeights::clear_ran_index() {
  _impl_.ran_index_ = 0u;
}
inline uint32_t SchedulingWeights::_internal_ran_index() const {
  return _impl_.ran_index_;
}
inline uint32_t SchedulingWeights::ran_index() const {
  // @@protoc_insertion_point(field_get:SchedulingWeights.ran_index)
  return _internal_ran_index();
}
inline void SchedulingWeights::_internal_set_ran_index(uint32_t value) {
  
  _impl_.ran_index_ = value;
}
inline void SchedulingWeights::set_ran_index(uint32_t value) {
  _internal_set_ran_index(value);
  // @@protoc_insertion_point(field_set:SchedulingWeights.ran_index)
}

// uint32 tti_index = 2;
inline void SchedulingWeights::clear_tti_index() {
  _impl_.tti_index_ = 0u;
}
inline uint32_t SchedulingWeights::_internal_tti_index() const {
  return _impl_.tti_index_;
}
inline uint32_t SchedulingWeights::tti_index() const {
  // @@protoc_insertion_point(field_get:SchedulingWeights.tti_index)
  return _internal_tti_index();
}
inline void SchedulingWeights::_internal_set_tti_index(uint32_t value) {
  
  _impl_.tti_index_ = value;
}
inline void SchedulingWeights::set_tti_index(uint32_t value) {
  _internal_set_tti_index(value);
  // @@protoc_insertion_point(field_set:SchedulingWeights.tti_index)
}

// repeated .UeWeight ue_weights = 3;
inline int SchedulingWeights::_internal_ue_weights_size() const {
  return _impl_.ue_weights_.size();
}
inline int SchedulingWeights::ue_weights_size() const {
  return _internal_ue_weights_size();
}
inline void SchedulingWeights::clear_ue_weights() {
  _impl_.ue_weights_.Clear();
}
inline ::UeWeight* SchedulingWeights::mutable_ue_weights(int index) {
  // @@protoc_insertion_point(field_mutable:SchedulingWeights.ue_weights)
  return _impl_.ue_weights_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UeWeight >*
SchedulingWeights::mutable_ue_weights() {
  // @@protoc_insertion_point(field_mutable_list:SchedulingWeights.ue_weights)
  return &_impl_.ue_weights_;
}
inline const ::UeWeight& SchedulingWeights::_internal_ue_weights(int index) const {
  return _impl_.ue_weights_.Get(index);
}
inline const ::UeWeight& SchedulingWeights::ue_weights(int index) const {
  // @@protoc_insertion_point(field_get:SchedulingWeights.ue_weights)
  return _internal_ue_weights(index);
}
inline ::UeWeight* SchedulingWeights::_internal_add_ue_weights() {
  return _impl_.ue_weights_.Add();
}
inline ::UeWeight* SchedulingWeights::add_ue_weights() {
  ::UeWeight* _add = _internal_add_ue_weights();
  // @@protoc_insertion_point(field_add:SchedulingWeights.ue_weights)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UeWeight >&
SchedulingWeights::ue_weights() const {
  // @@protoc_insertion_point(field_list:SchedulingWeights.ue_weights)
  return _impl_.ue_weights_;
}

// -------------------------------------------------------------------

// UeWeight

// uint32 rnti = 1;
inline void UeWeight::clear_rnti() {
  _impl_.rnti_ = 0u;
}
inline uint32_t UeWeight::_internal_rnti() const {
  return _impl_.rnti_;
}
inline uint32_t UeWeight::rnti() const {
  // @@protoc_insertion_point(field_get:UeWeight.rnti)
  return _internal_rnti();
}
inline void UeWeight::_internal_set_rnti(uint32_t value) {
  
  _impl_.rnti_ = value;
}
inline void UeWeight::set_rnti(uint32_t value) {
  _internal_set_rnti(value);
  // @@protoc_insertion_point(field_set:UeWeight.rnti)
}

// float weight = 2;
inline void UeWeight::clear_weight() {
  _impl_.weight_ = 0;
}
inline float UeWeight::_internal_weight() const {
  return _impl_.weight_;
}
inline float UeWeight::weight() const {
  // @@protoc_insertion_point(field_get:UeWeight.weight)
  return _internal_weight();
}
inline void UeWeight::_internal_set_weight(float value) {
  
  _impl_.weight_ = value;
}
inline void UeWeight::set_weight(float value) {
  _internal_set_weight(value);
  // @@protoc_insertion_point(field_set:UeWeight.weight)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_control_5fweights_2eproto
