// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control_mcs.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_control_5fmcs_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_control_5fmcs_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_control_5fmcs_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_control_5fmcs_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_control_5fmcs_2eproto;
class McsControl;
struct McsControlDefaultTypeInternal;
extern McsControlDefaultTypeInternal _McsControl_default_instance_;
class UeMcs;
struct UeMcsDefaultTypeInternal;
extern UeMcsDefaultTypeInternal _UeMcs_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::McsControl* Arena::CreateMaybeMessage<::McsControl>(Arena*);
template<> ::UeMcs* Arena::CreateMaybeMessage<::UeMcs>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class McsControl final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:McsControl) */ {
 public:
  inline McsControl() : McsControl(nullptr) {}
  ~McsControl() override;
  explicit PROTOBUF_CONSTEXPR McsControl(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  McsControl(const McsControl& from);
  McsControl(McsControl&& from) noexcept
    : McsControl() {
    *this = ::std::move(from);
  }

  inline McsControl& operator=(const McsControl& from) {
    CopyFrom(from);
    return *this;
  }
  inline McsControl& operator=(McsControl&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const McsControl& default_instance() {
    return *internal_default_instance();
  }
  static inline const McsControl* internal_default_instance() {
    return reinterpret_cast<const McsControl*>(
               &_McsControl_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(McsControl& a, McsControl& b) {
    a.Swap(&b);
  }
  inline void Swap(McsControl* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(McsControl* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  McsControl* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<McsControl>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const McsControl& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const McsControl& from) {
    McsControl::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(McsControl* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "McsControl";
  }
  protected:
  explicit McsControl(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUeMcsFieldNumber = 3,
    kRanIndexFieldNumber = 1,
    kTtiIndexFieldNumber = 2,
  };
  // repeated .UeMcs ue_mcs = 3;
  int ue_mcs_size() const;
  private:
  int _internal_ue_mcs_size() const;
  public:
  void clear_ue_mcs();
  ::UeMcs* mutable_ue_mcs(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UeMcs >*
      mutable_ue_mcs();
  private:
  const ::UeMcs& _internal_ue_mcs(int index) const;
  ::UeMcs* _internal_add_ue_mcs();
  public:
  const ::UeMcs& ue_mcs(int index) const;
  ::UeMcs* add_ue_mcs();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UeMcs >&
      ue_mcs() const;

  // uint32 ran_index = 1;
  void clear_ran_index();
  uint32_t ran_index() const;
  void set_ran_index(uint32_t value);
  private:
  uint32_t _internal_ran_index() const;
  void _internal_set_ran_index(uint32_t value);
  public:

  // uint32 tti_index = 2;
  void clear_tti_index();
  uint32_t tti_index() const;
  void set_tti_index(uint32_t value);
  private:
  uint32_t _internal_tti_index() const;
  void _internal_set_tti_index(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:McsControl)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UeMcs > ue_mcs_;
    uint32_t ran_index_;
    uint32_t tti_index_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_control_5fmcs_2eproto;
};
// -------------------------------------------------------------------

class UeMcs final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:UeMcs) */ {
 public:
  inline UeMcs() : UeMcs(nullptr) {}
  ~UeMcs() override;
  explicit PROTOBUF_CONSTEXPR UeMcs(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UeMcs(const UeMcs& from);
  UeMcs(UeMcs&& from) noexcept
    : UeMcs() {
    *this = ::std::move(from);
  }

  inline UeMcs& operator=(const UeMcs& from) {
    CopyFrom(from);
    return *this;
  }
  inline UeMcs& operator=(UeMcs&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UeMcs& default_instance() {
    return *internal_default_instance();
  }
  static inline const UeMcs* internal_default_instance() {
    return reinterpret_cast<const UeMcs*>(
               &_UeMcs_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(UeMcs& a, UeMcs& b) {
    a.Swap(&b);
  }
  inline void Swap(UeMcs* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UeMcs* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UeMcs* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UeMcs>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UeMcs& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UeMcs& from) {
    UeMcs::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UeMcs* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "UeMcs";
  }
  protected:
  explicit UeMcs(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRntiFieldNumber = 1,
    kMcsFieldNumber = 2,
  };
  // uint32 rnti = 1;
  void clear_rnti();
  uint32_t rnti() const;
  void set_rnti(uint32_t value);
  private:
  uint32_t _internal_rnti() const;
  void _internal_set_rnti(uint32_t value);
  public:

  // uint32 mcs = 2;
  void clear_mcs();
  uint32_t mcs() const;
  void set_mcs(uint32_t value);
  private:
  uint32_t _internal_mcs() const;
  void _internal_set_mcs(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:UeMcs)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t rnti_;
    uint32_t mcs_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_control_5fmcs_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// McsControl

// uint32 ran_index = 1;
inline void McsControl::clear_ran_index() {
  _impl_.ran_index_ = 0u;
}
inline uint32_t McsControl::_internal_ran_index() const {
  return _impl_.ran_index_;
}
inline uint32_t McsControl::ran_index() const {
  // @@protoc_insertion_point(field_get:McsControl.ran_index)
  return _internal_ran_index();
}
inline void McsControl::_internal_set_ran_index(uint32_t value) {
  
  _impl_.ran_index_ = value;
}
inline void McsControl::set_ran_index(uint32_t value) {
  _internal_set_ran_index(value);
  // @@protoc_insertion_point(field_set:McsControl.ran_index)
}

// uint32 tti_index = 2;
inline void McsControl::clear_tti_index() {
  _impl_.tti_index_ = 0u;
}
inline uint32_t McsControl::_internal_tti_index() const {
  return _impl_.tti_index_;
}
inline uint32_t McsControl::tti_index() const {
  // @@protoc_insertion_point(field_get:McsControl.tti_index)
  return _internal_tti_index();
}
inline void McsControl::_internal_set_tti_index(uint32_t value) {
  
  _impl_.tti_index_ = value;
}
inline void McsControl::set_tti_index(uint32_t value) {
  _internal_set_tti_index(value);
  // @@protoc_insertion_point(field_set:McsControl.tti_index)
}

// repeated .UeMcs ue_mcs = 3;
inline int McsControl::_internal_ue_mcs_size() const {
  return _impl_.ue_mcs_.size();
}
inline int McsControl::ue_mcs_size() const {
  return _internal_ue_mcs_size();
}
inline void McsControl::clear_ue_mcs() {
  _impl_.ue_mcs_.Clear();
}
inline ::UeMcs* McsControl::mutable_ue_mcs(int index) {
  // @@protoc_insertion_point(field_mutable:McsControl.ue_mcs)
  return _impl_.ue_mcs_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UeMcs >*
McsControl::mutable_ue_mcs() {
  // @@protoc_insertion_point(field_mutable_list:McsControl.ue_mcs)
  return &_impl_.ue_mcs_;
}
inline const ::UeMcs& McsControl::_internal_ue_mcs(int index) const {
  return _impl_.ue_mcs_.Get(index);
}
inline const ::UeMcs& McsControl::ue_mcs(int index) const {
  // @@protoc_insertion_point(field_get:McsControl.ue_mcs)
  return _internal_ue_mcs(index);
}
inline ::UeMcs* McsControl::_internal_add_ue_mcs() {
  return _impl_.ue_mcs_.Add();
}
inline ::UeMcs* McsControl::add_ue_mcs() {
  ::UeMcs* _add = _internal_add_ue_mcs();
  // @@protoc_insertion_point(field_add:McsControl.ue_mcs)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UeMcs >&
McsControl::ue_mcs() const {
  // @@protoc_insertion_point(field_list:McsControl.ue_mcs)
  return _impl_.ue_mcs_;
}

// -------------------------------------------------------------------

// UeMcs

// uint32 rnti = 1;
inline void UeMcs::clear_rnti() {
  _impl_.rnti_ = 0u;
}
inline uint32_t UeMcs::_internal_rnti() const {
  return _impl_.rnti_;
}
inline uint32_t UeMcs::rnti() const {
  // @@protoc_insertion_point(field_get:UeMcs.rnti)
  return _internal_rnti();
}
inline void UeMcs::_internal_set_rnti(uint32_t value) {
  
  _impl_.rnti_ = value;
}
inline void UeMcs::set_rnti(uint32_t value) {
  _internal_set_rnti(value);
  // @@protoc_insertion_point(field_set:UeMcs.rnti)
}

// uint32 mcs = 2;
inline void UeMcs::clear_mcs() {
  _impl_.mcs_ = 0u;
}
inline uint32_t UeMcs::_internal_mcs() const {
  return _impl_.mcs_;
}
inline uint32_t UeMcs::mcs() const {
  // @@protoc_insertion_point(field_get:UeMcs.mcs)
  return _internal_mcs();
}
inline void UeMcs::_internal_set_mcs(uint32_t value) {
  
  _impl_.mcs_ = value;
}
inline void UeMcs::set_mcs(uint32_t value) {
  _internal_set_mcs(value);
  // @@protoc_insertion_point(field_set:UeMcs.mcs)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_control_5fmcs_2eproto
