// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control_mcs.proto

#include "control_mcs.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR McsControl::McsControl(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ue_mcs_)*/{}
  , /*decltype(_impl_.ran_index_)*/0u
  , /*decltype(_impl_.tti_index_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct McsControlDefaultTypeInternal {
  PROTOBUF_CONSTEXPR McsControlDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~McsControlDefaultTypeInternal() {}
  union {
    McsControl _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 McsControlDefaultTypeInternal _McsControl_default_instance_;
PROTOBUF_CONSTEXPR UeMcs::UeMcs(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.rnti_)*/0u
  , /*decltype(_impl_.mcs_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UeMcsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UeMcsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UeMcsDefaultTypeInternal() {}
  union {
    UeMcs _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UeMcsDefaultTypeInternal _UeMcs_default_instance_;
static ::_pb::Metadata file_level_metadata_control_5fmcs_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_control_5fmcs_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_control_5fmcs_2eproto = nullptr;

const uint32_t TableStruct_control_5fmcs_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::McsControl, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::McsControl, _impl_.ran_index_),
  PROTOBUF_FIELD_OFFSET(::McsControl, _impl_.tti_index_),
  PROTOBUF_FIELD_OFFSET(::McsControl, _impl_.ue_mcs_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::UeMcs, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::UeMcs, _impl_.rnti_),
  PROTOBUF_FIELD_OFFSET(::UeMcs, _impl_.mcs_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::McsControl)},
  { 9, -1, -1, sizeof(::UeMcs)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_McsControl_default_instance_._instance,
  &::_UeMcs_default_instance_._instance,
};

const char descriptor_table_protodef_control_5fmcs_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021control_mcs.proto\"J\n\nMcsControl\022\021\n\tran"
  "_index\030\001 \001(\r\022\021\n\ttti_index\030\002 \001(\r\022\026\n\006ue_mc"
  "s\030\003 \003(\0132\006.UeMcs\"\"\n\005UeMcs\022\014\n\004rnti\030\001 \001(\r\022\013"
  "\n\003mcs\030\002 \001(\rb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_control_5fmcs_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_control_5fmcs_2eproto = {
    false, false, 139, descriptor_table_protodef_control_5fmcs_2eproto,
    "control_mcs.proto",
    &descriptor_table_control_5fmcs_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_control_5fmcs_2eproto::offsets,
    file_level_metadata_control_5fmcs_2eproto, file_level_enum_descriptors_control_5fmcs_2eproto,
    file_level_service_descriptors_control_5fmcs_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_control_5fmcs_2eproto_getter() {
  return &descriptor_table_control_5fmcs_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_control_5fmcs_2eproto(&descriptor_table_control_5fmcs_2eproto);

// ===================================================================

class McsControl::_Internal {
 public:
};

McsControl::McsControl(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:McsControl)
}
McsControl::McsControl(const McsControl& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  McsControl* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ue_mcs_){from._impl_.ue_mcs_}
    , decltype(_impl_.ran_index_){}
    , decltype(_impl_.tti_index_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.ran_index_, &from._impl_.ran_index_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.tti_index_) -
    reinterpret_cast<char*>(&_impl_.ran_index_)) + sizeof(_impl_.tti_index_));
  // @@protoc_insertion_point(copy_constructor:McsControl)
}

inline void McsControl::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ue_mcs_){arena}
    , decltype(_impl_.ran_index_){0u}
    , decltype(_impl_.tti_index_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

McsControl::~McsControl() {
  // @@protoc_insertion_point(destructor:McsControl)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void McsControl::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.ue_mcs_.~RepeatedPtrField();
}

void McsControl::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void McsControl::Clear() {
// @@protoc_insertion_point(message_clear_start:McsControl)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ue_mcs_.Clear();
  ::memset(&_impl_.ran_index_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.tti_index_) -
      reinterpret_cast<char*>(&_impl_.ran_index_)) + sizeof(_impl_.tti_index_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* McsControl::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 ran_index = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.ran_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 tti_index = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.tti_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .UeMcs ue_mcs = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_ue_mcs(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* McsControl::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:McsControl)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ran_index = 1;
  if (this->_internal_ran_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_ran_index(), target);
  }

  // uint32 tti_index = 2;
  if (this->_internal_tti_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_tti_index(), target);
  }

  // repeated .UeMcs ue_mcs = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_ue_mcs_size()); i < n; i++) {
    const auto& repfield = this->_internal_ue_mcs(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:McsControl)
  return target;
}

size_t McsControl::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:McsControl)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .UeMcs ue_mcs = 3;
  total_size += 1UL * this->_internal_ue_mcs_size();
  for (const auto& msg : this->_impl_.ue_mcs_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 ran_index = 1;
  if (this->_internal_ran_index() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_ran_index());
  }

  // uint32 tti_index = 2;
  if (this->_internal_tti_index() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_tti_index());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData McsControl::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    McsControl::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*McsControl::GetClassData() const { return &_class_data_; }


void McsControl::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<McsControl*>(&to_msg);
  auto& from = static_cast<const McsControl&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:McsControl)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.ue_mcs_.MergeFrom(from._impl_.ue_mcs_);
  if (from._internal_ran_index() != 0) {
    _this->_internal_set_ran_index(from._internal_ran_index());
  }
  if (from._internal_tti_index() != 0) {
    _this->_internal_set_tti_index(from._internal_tti_index());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void McsControl::CopyFrom(const McsControl& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:McsControl)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool McsControl::IsInitialized() const {
  return true;
}

void McsControl::InternalSwap(McsControl* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.ue_mcs_.InternalSwap(&other->_impl_.ue_mcs_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(McsControl, _impl_.tti_index_)
      + sizeof(McsControl::_impl_.tti_index_)
      - PROTOBUF_FIELD_OFFSET(McsControl, _impl_.ran_index_)>(
          reinterpret_cast<char*>(&_impl_.ran_index_),
          reinterpret_cast<char*>(&other->_impl_.ran_index_));
}

::PROTOBUF_NAMESPACE_ID::Metadata McsControl::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_control_5fmcs_2eproto_getter, &descriptor_table_control_5fmcs_2eproto_once,
      file_level_metadata_control_5fmcs_2eproto[0]);
}

// ===================================================================

class UeMcs::_Internal {
 public:
};

UeMcs::UeMcs(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:UeMcs)
}
UeMcs::UeMcs(const UeMcs& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UeMcs* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.rnti_){}
    , decltype(_impl_.mcs_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.rnti_, &from._impl_.rnti_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.mcs_) -
    reinterpret_cast<char*>(&_impl_.rnti_)) + sizeof(_impl_.mcs_));
  // @@protoc_insertion_point(copy_constructor:UeMcs)
}

inline void UeMcs::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.rnti_){0u}
    , decltype(_impl_.mcs_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

UeMcs::~UeMcs() {
  // @@protoc_insertion_point(destructor:UeMcs)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UeMcs::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void UeMcs::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UeMcs::Clear() {
// @@protoc_insertion_point(message_clear_start:UeMcs)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.rnti_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.mcs_) -
      reinterpret_cast<char*>(&_impl_.rnti_)) + sizeof(_impl_.mcs_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UeMcs::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 rnti = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.rnti_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 mcs = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.mcs_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UeMcs::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:UeMcs)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 rnti = 1;
  if (this->_internal_rnti() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_rnti(), target);
  }

  // uint32 mcs = 2;
  if (this->_internal_mcs() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_mcs(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:UeMcs)
  return target;
}

size_t UeMcs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:UeMcs)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 rnti = 1;
  if (this->_internal_rnti() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_rnti());
  }

  // uint32 mcs = 2;
  if (this->_internal_mcs() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_mcs());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UeMcs::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UeMcs::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UeMcs::GetClassData() const { return &_class_data_; }


void UeMcs::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UeMcs*>(&to_msg);
  auto& from = static_cast<const UeMcs&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:UeMcs)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_rnti() != 0) {
    _this->_internal_set_rnti(from._internal_rnti());
  }
  if (from._internal_mcs() != 0) {
    _this->_internal_set_mcs(from._internal_mcs());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UeMcs::CopyFrom(const UeMcs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:UeMcs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UeMcs::IsInitialized() const {
  return true;
}

void UeMcs::InternalSwap(UeMcs* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UeMcs, _impl_.mcs_)
      + sizeof(UeMcs::_impl_.mcs_)
      - PROTOBUF_FIELD_OFFSET(UeMcs, _impl_.rnti_)>(
          reinterpret_cast<char*>(&_impl_.rnti_),
          reinterpret_cast<char*>(&other->_impl_.rnti_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UeMcs::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_control_5fmcs_2eproto_getter, &descriptor_table_control_5fmcs_2eproto_once,
      file_level_metadata_control_5fmcs_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::McsControl*
Arena::CreateMaybeMessage< ::McsControl >(Arena* arena) {
  return Arena::CreateMessageInternal< ::McsControl >(arena);
}
template<> PROTOBUF_NOINLINE ::UeMcs*
Arena::CreateMaybeMessage< ::UeMcs >(Arena* arena) {
  return Arena::CreateMessageInternal< ::UeMcs >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
