// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control_weights.proto

#include "control_weights.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR SchedulingWeights::SchedulingWeights(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ue_weights_)*/{}
  , /*decltype(_impl_.ran_index_)*/0u
  , /*decltype(_impl_.tti_index_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SchedulingWeightsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SchedulingWeightsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SchedulingWeightsDefaultTypeInternal() {}
  union {
    SchedulingWeights _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SchedulingWeightsDefaultTypeInternal _SchedulingWeights_default_instance_;
PROTOBUF_CONSTEXPR UeWeight::UeWeight(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.rnti_)*/0u
  , /*decltype(_impl_.weight_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UeWeightDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UeWeightDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UeWeightDefaultTypeInternal() {}
  union {
    UeWeight _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UeWeightDefaultTypeInternal _UeWeight_default_instance_;
static ::_pb::Metadata file_level_metadata_control_5fweights_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_control_5fweights_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_control_5fweights_2eproto = nullptr;

const uint32_t TableStruct_control_5fweights_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::SchedulingWeights, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::SchedulingWeights, _impl_.ran_index_),
  PROTOBUF_FIELD_OFFSET(::SchedulingWeights, _impl_.tti_index_),
  PROTOBUF_FIELD_OFFSET(::SchedulingWeights, _impl_.ue_weights_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::UeWeight, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::UeWeight, _impl_.rnti_),
  PROTOBUF_FIELD_OFFSET(::UeWeight, _impl_.weight_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::SchedulingWeights)},
  { 9, -1, -1, sizeof(::UeWeight)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_SchedulingWeights_default_instance_._instance,
  &::_UeWeight_default_instance_._instance,
};

const char descriptor_table_protodef_control_5fweights_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025control_weights.proto\"X\n\021SchedulingWei"
  "ghts\022\021\n\tran_index\030\001 \001(\r\022\021\n\ttti_index\030\002 \001"
  "(\r\022\035\n\nue_weights\030\003 \003(\0132\t.UeWeight\"(\n\010UeW"
  "eight\022\014\n\004rnti\030\001 \001(\r\022\016\n\006weight\030\002 \001(\002b\006pro"
  "to3"
  ;
static ::_pbi::once_flag descriptor_table_control_5fweights_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_control_5fweights_2eproto = {
    false, false, 163, descriptor_table_protodef_control_5fweights_2eproto,
    "control_weights.proto",
    &descriptor_table_control_5fweights_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_control_5fweights_2eproto::offsets,
    file_level_metadata_control_5fweights_2eproto, file_level_enum_descriptors_control_5fweights_2eproto,
    file_level_service_descriptors_control_5fweights_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_control_5fweights_2eproto_getter() {
  return &descriptor_table_control_5fweights_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_control_5fweights_2eproto(&descriptor_table_control_5fweights_2eproto);

// ===================================================================

class SchedulingWeights::_Internal {
 public:
};

SchedulingWeights::SchedulingWeights(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:SchedulingWeights)
}
SchedulingWeights::SchedulingWeights(const SchedulingWeights& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SchedulingWeights* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ue_weights_){from._impl_.ue_weights_}
    , decltype(_impl_.ran_index_){}
    , decltype(_impl_.tti_index_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.ran_index_, &from._impl_.ran_index_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.tti_index_) -
    reinterpret_cast<char*>(&_impl_.ran_index_)) + sizeof(_impl_.tti_index_));
  // @@protoc_insertion_point(copy_constructor:SchedulingWeights)
}

inline void SchedulingWeights::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ue_weights_){arena}
    , decltype(_impl_.ran_index_){0u}
    , decltype(_impl_.tti_index_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SchedulingWeights::~SchedulingWeights() {
  // @@protoc_insertion_point(destructor:SchedulingWeights)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SchedulingWeights::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.ue_weights_.~RepeatedPtrField();
}

void SchedulingWeights::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SchedulingWeights::Clear() {
// @@protoc_insertion_point(message_clear_start:SchedulingWeights)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ue_weights_.Clear();
  ::memset(&_impl_.ran_index_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.tti_index_) -
      reinterpret_cast<char*>(&_impl_.ran_index_)) + sizeof(_impl_.tti_index_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SchedulingWeights::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 ran_index = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.ran_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 tti_index = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.tti_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .UeWeight ue_weights = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_ue_weights(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SchedulingWeights::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SchedulingWeights)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ran_index = 1;
  if (this->_internal_ran_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_ran_index(), target);
  }

  // uint32 tti_index = 2;
  if (this->_internal_tti_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_tti_index(), target);
  }

  // repeated .UeWeight ue_weights = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_ue_weights_size()); i < n; i++) {
    const auto& repfield = this->_internal_ue_weights(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SchedulingWeights)
  return target;
}

size_t SchedulingWeights::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SchedulingWeights)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .UeWeight ue_weights = 3;
  total_size += 1UL * this->_internal_ue_weights_size();
  for (const auto& msg : this->_impl_.ue_weights_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 ran_index = 1;
  if (this->_internal_ran_index() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_ran_index());
  }

  // uint32 tti_index = 2;
  if (this->_internal_tti_index() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_tti_index());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SchedulingWeights::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SchedulingWeights::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SchedulingWeights::GetClassData() const { return &_class_data_; }


void SchedulingWeights::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SchedulingWeights*>(&to_msg);
  auto& from = static_cast<const SchedulingWeights&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SchedulingWeights)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.ue_weights_.MergeFrom(from._impl_.ue_weights_);
  if (from._internal_ran_index() != 0) {
    _this->_internal_set_ran_index(from._internal_ran_index());
  }
  if (from._internal_tti_index() != 0) {
    _this->_internal_set_tti_index(from._internal_tti_index());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SchedulingWeights::CopyFrom(const SchedulingWeights& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SchedulingWeights)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SchedulingWeights::IsInitialized() const {
  return true;
}

void SchedulingWeights::InternalSwap(SchedulingWeights* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.ue_weights_.InternalSwap(&other->_impl_.ue_weights_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SchedulingWeights, _impl_.tti_index_)
      + sizeof(SchedulingWeights::_impl_.tti_index_)
      - PROTOBUF_FIELD_OFFSET(SchedulingWeights, _impl_.ran_index_)>(
          reinterpret_cast<char*>(&_impl_.ran_index_),
          reinterpret_cast<char*>(&other->_impl_.ran_index_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SchedulingWeights::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_control_5fweights_2eproto_getter, &descriptor_table_control_5fweights_2eproto_once,
      file_level_metadata_control_5fweights_2eproto[0]);
}

// ===================================================================

class UeWeight::_Internal {
 public:
};

UeWeight::UeWeight(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:UeWeight)
}
UeWeight::UeWeight(const UeWeight& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UeWeight* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.rnti_){}
    , decltype(_impl_.weight_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.rnti_, &from._impl_.rnti_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.weight_) -
    reinterpret_cast<char*>(&_impl_.rnti_)) + sizeof(_impl_.weight_));
  // @@protoc_insertion_point(copy_constructor:UeWeight)
}

inline void UeWeight::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.rnti_){0u}
    , decltype(_impl_.weight_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

UeWeight::~UeWeight() {
  // @@protoc_insertion_point(destructor:UeWeight)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UeWeight::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void UeWeight::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UeWeight::Clear() {
// @@protoc_insertion_point(message_clear_start:UeWeight)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.rnti_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.weight_) -
      reinterpret_cast<char*>(&_impl_.rnti_)) + sizeof(_impl_.weight_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UeWeight::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 rnti = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.rnti_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float weight = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.weight_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UeWeight::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:UeWeight)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 rnti = 1;
  if (this->_internal_rnti() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_rnti(), target);
  }

  // float weight = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_weight = this->_internal_weight();
  uint32_t raw_weight;
  memcpy(&raw_weight, &tmp_weight, sizeof(tmp_weight));
  if (raw_weight != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_weight(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:UeWeight)
  return target;
}

size_t UeWeight::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:UeWeight)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 rnti = 1;
  if (this->_internal_rnti() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_rnti());
  }

  // float weight = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_weight = this->_internal_weight();
  uint32_t raw_weight;
  memcpy(&raw_weight, &tmp_weight, sizeof(tmp_weight));
  if (raw_weight != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UeWeight::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UeWeight::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UeWeight::GetClassData() const { return &_class_data_; }


void UeWeight::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UeWeight*>(&to_msg);
  auto& from = static_cast<const UeWeight&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:UeWeight)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_rnti() != 0) {
    _this->_internal_set_rnti(from._internal_rnti());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_weight = from._internal_weight();
  uint32_t raw_weight;
  memcpy(&raw_weight, &tmp_weight, sizeof(tmp_weight));
  if (raw_weight != 0) {
    _this->_internal_set_weight(from._internal_weight());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UeWeight::CopyFrom(const UeWeight& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:UeWeight)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UeWeight::IsInitialized() const {
  return true;
}

void UeWeight::InternalSwap(UeWeight* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UeWeight, _impl_.weight_)
      + sizeof(UeWeight::_impl_.weight_)
      - PROTOBUF_FIELD_OFFSET(UeWeight, _impl_.rnti_)>(
          reinterpret_cast<char*>(&_impl_.rnti_),
          reinterpret_cast<char*>(&other->_impl_.rnti_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UeWeight::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_control_5fweights_2eproto_getter, &descriptor_table_control_5fweights_2eproto_once,
      file_level_metadata_control_5fweights_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::SchedulingWeights*
Arena::CreateMaybeMessage< ::SchedulingWeights >(Arena* arena) {
  return Arena::CreateMessageInternal< ::SchedulingWeights >(arena);
}
template<> PROTOBUF_NOINLINE ::UeWeight*
Arena::CreateMaybeMessage< ::UeWeight >(Arena* arena) {
  return Arena::CreateMessageInternal< ::UeWeight >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
