# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control_weights.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ontrol_weights.proto\"X\n\x11SchedulingWeights\x12\x11\n\tran_index\x18\x01 \x01(\r\x12\x11\n\ttti_index\x18\x02 \x01(\r\x12\x1d\n\nue_weights\x18\x03 \x03(\x0b\x32\t.UeWeight\"(\n\x08UeWeight\x12\x0c\n\x04rnti\x18\x01 \x01(\r\x12\x0e\n\x06weight\x18\x02 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_weights_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCHEDULINGWEIGHTS._serialized_start=25
  _SCHEDULINGWEIGHTS._serialized_end=113
  _UEWEIGHT._serialized_start=115
  _UEWEIGHT._serialized_end=155
# @@protoc_insertion_point(module_scope)
