# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control_mcs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63ontrol_mcs.proto\"J\n\nMcsControl\x12\x11\n\tran_index\x18\x01 \x01(\r\x12\x11\n\ttti_index\x18\x02 \x01(\r\x12\x16\n\x06ue_mcs\x18\x03 \x03(\x0b\x32\x06.UeMcs\"\"\n\x05UeMcs\x12\x0c\n\x04rnti\x18\x01 \x01(\r\x12\x0b\n\x03mcs\x18\x02 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_mcs_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MCSCONTROL._serialized_start=21
  _MCSCONTROL._serialized_end=95
  _UEMCS._serialized_start=97
  _UEMCS._serialized_end=131
# @@protoc_insertion_point(module_scope)
